#-------------------------------------------------------------------------
#
# Makefile for backend/unittest
#
# src/backend/unittest/backend/stub/utils/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/unittest/backend/stub/utils/
top_builddir = ../../../../../..
include $(top_builddir)/src/Makefile.global

SUBDIRS = cache
include $(top_srcdir)/src/backend/common.mk
