#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for utils/hll
#
# IDENTIFICATION
#    src/backend/utils/hll/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/utils/hll
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = hll_userfuncs.o

include $(top_srcdir)/src/backend/common.mk