#-------------------------------------------------------------------------
#
# Makefile for backend/unittest
#
# src/backend/unittest/backend/access/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/unittest/backend/access/
top_builddir = ../../../../../
include $(top_builddir)/src/Makefile.global

SUBDIRS = transam
include $(top_srcdir)/src/backend/common.mk

clean:
	rm -rf $(UNIT_OBJS)
