drop table if exists test_vec;
create table test_vec(i int2);
insert into test_vec values (generate_series(-10,15));
select avg(i) from test_vec;
select sum(i) from test_vec;
select max(i) from test_vec;
select min(i) from test_vec;
drop table if exists test_vec;
create table test_vec(i int4);
insert into test_vec values (generate_series(-10,15));
select avg(i) from test_vec;
select sum(i) from test_vec;
select max(i) from test_vec;
select min(i) from test_vec;
drop table if exists test_vec;
create table test_vec(i int8);
insert into test_vec values (generate_series(-10,15));
select avg(i) from test_vec;
select sum(i) from test_vec;
select max(i) from test_vec;
select min(i) from test_vec;
drop table if exists test_vec;
create table test_vec(i float4);
insert into test_vec values (generate_series(-10,15));
select avg(i) from test_vec;
select sum(i) from test_vec;
select max(i) from test_vec;
select min(i) from test_vec;
drop table if exists test_vec;
create table test_vec(i float8);
insert into test_vec values (generate_series(-10,15));
select avg(i) from test_vec;
select sum(i) from test_vec;
select max(i) from test_vec;
select min(i) from test_vec;
drop table if exists test_vec;
create table test_vec(i numeric);
insert into test_vec values (generate_series(-10,15));
select avg(i) from test_vec;
select sum(i) from test_vec;
select max(i) from test_vec;
select min(i) from test_vec;
insert into test_vec values (9223372036854775808);
select avg(i) from test_vec;
select sum(i) from test_vec;
select max(i) from test_vec;
select min(i) from test_vec;
insert into test_vec values (170141183460469231731687303715884105728);
select avg(i) from test_vec;
select sum(i) from test_vec;
select max(i) from test_vec;
select min(i) from test_vec;
drop table if exists test_vec;
create table test_vec(i oid);
insert into test_vec values (generate_series(1,10));
select avg(i) from test_vec;
select sum(i) from test_vec;
select max(i) from test_vec;
select min(i) from test_vec;
drop table if exists test_vec;
create table test_vec(i date);
insert into test_vec values ('1957-04-09');
insert into test_vec values ('1957-06-13');
select avg(i) from test_vec;
set datestyle = 'ISO, YMD';
-- select sum(i) from test_vec;
select max(i) from test_vec;
select min(i) from test_vec;
drop table if exists test_vec;
create table test_vec(i time);
insert into test_vec values ('00:00');
insert into test_vec values ('01:00');
select avg(i) from test_vec;
select sum(i) from test_vec;
select max(i) from test_vec;
select min(i) from test_vec;
drop table if exists test_vec;
create table test_vec(i time with time zone);
insert into test_vec values ('00:01 PDT');
insert into test_vec values ('01:00 PDT');
select avg(i) from test_vec;
select sum(i) from test_vec;
select max(i) from test_vec;
select min(i) from test_vec;
drop table if exists test_vec;
create table test_vec(i text);
insert into test_vec values ('hello world');
insert into test_vec values ('goodbye world');
set enable_lightweight_ora_syntax = on;
select avg(i) from test_vec;
set enable_lightweight_ora_syntax = off;
-- select sum(i) from test_vec;
select max(i) from test_vec;
select min(i) from test_vec;
drop table if exists test_vec;
create table test_vec(i bpchar);
insert into test_vec values ('a');
insert into test_vec values ('A');
select avg(i) from test_vec;
-- select sum(i) from test_vec;
select max(i) from test_vec;
select min(i) from test_vec;
drop table if exists test_vec;
create table test_vec(i money);
insert into test_vec values ('$223.459');
insert into test_vec values ('$323.459');
select avg(i) from test_vec;
select sum(i) from test_vec;
select max(i) from test_vec;
select min(i) from test_vec;
SET DATESTYLE = 'ISO';
SET IntervalStyle to postgres;
drop table if exists test_vec;
create table test_vec(i interval);
insert into test_vec (i) values ('@ 1 minute');
insert into test_vec (i) values ('@ 5 hour');
insert into test_vec (i) values ('@ 10 day');
insert into test_vec (i) values ('@ 34 year');
insert into test_vec (i) values ('@ 3 months');
insert into test_vec (i) values ('@ 14 seconds ago');
insert into test_vec (i) values ('1 day 2 hours 3 minutes 4 seconds');
insert into test_vec (i) values ('6 years');
insert into test_vec (i) values ('5 months');
insert into test_vec (i) values ('5 months 12 hours');
select avg(i) from test_vec;
select sum(i) from test_vec;
select max(i) from test_vec;
select min(i) from test_vec;
drop table if exists test_vec;
RESET DATESTYLE;
RESET IntervalStyle;
create table test_vec(i timestamp);
insert into test_vec values ('2022-06-28 11:42:42.970617');
insert into test_vec values ('2022-06-28 00:00:00');
select avg(i) from test_vec;
-- select sum(i) from test_vec;
select max(i) from test_vec;
select min(i) from test_vec;
drop table if exists test_vec;
create table test_vec(i int2[]);
insert into test_vec values ('{1,2,3,4,5}' );
insert into test_vec values ('{6,7,8,9,10}' );
select avg(i) from test_vec;
select sum(i) from test_vec;
select max(i) from test_vec;
select min(i) from test_vec;
drop table if exists test_vec;
create table test_vec (c cidr, i inet);
insert into test_vec values ('192.168.1', '192.168.1.226/24');
insert into test_vec values ('192.168.1.0/26', '192.168.1.226');
select avg(i) from test_vec;
select sum(i) from test_vec;
select max(i) from test_vec;
select min(i) from test_vec;
drop table if exists test_vec;

-- 1020385652107939887
create table bug_count_distinct_toast(f1 int,f2 text,f3 varchar(32),f4 varchar(160),f5 varchar(320),primary key (f1));
alter table bug_count_distinct_toast alter column f2 set storage EXTERNAL;
insert into bug_count_distinct_toast select t,repeat('或者无法得到更好的结果的时候才停止',1000),md5(random()::text),repeat(md5(random()::text),5),repeat(md5(random()::text),10) from generate_series(1,10) as t;
insert into bug_count_distinct_toast select t,repeat('无法得到更好的结果',1000),md5(random()::text),repeat(md5(random()::text),5),repeat(md5(random()::text),10) from generate_series(11,20) as t;
explain (verbose, costs off) select count(distinct f2) from bug_count_distinct_toast;
select count(distinct f2) from bug_count_distinct_toast;
set distinct_with_hash = off;
explain (verbose, costs off) select count(distinct f2) from bug_count_distinct_toast;
select count(distinct f2) from bug_count_distinct_toast;
reset distinct_with_hash;

drop table bug_count_distinct_toast;
