#暂未创建GNU make的其他特性

#AIX默认构建第一个规则的*every*目标。从开始
#单个目标的空规则，使其他目标成为非默认目标。
#添加要求“SQL PARSER”的文件
all:

all install clean oracle-check oracle-installcheck:
	@echo "尽可能的使用GNU make才能使用Postgres。后续添加"
	@echo "在名为“gmake”的系统上"
