/*-------------------------------------------------------------------------
 *
 * pg_extprotocol_d.h
 *    Macro definitions for pg_extprotocol
 *
 * Portions Copyright (c) 1996-2019, PostgreSQL Global Development Group
 * Portions Copyright (c) 1994, Regents of the University of California
 *
 * NOTES
 *  ******************************
 *  *** DO NOT EDIT THIS FILE! ***
 *  ******************************
 *
 *  It has been GENERATED by src/backend/catalog/genbki.pl
 *
 *-------------------------------------------------------------------------
 */
#ifndef PG_EXTPROTOCOL_D_H
#define PG_EXTPROTOCOL_D_H

#define ExtprotocolRelationId 7175

#define Anum_pg_extprotocol_oid 1
#define Anum_pg_extprotocol_ptcname 2
#define Anum_pg_extprotocol_ptcreadfn 3
#define Anum_pg_extprotocol_ptcwritefn 4
#define Anum_pg_extprotocol_ptcvalidatorfn 5
#define Anum_pg_extprotocol_ptcowner 6
#define Anum_pg_extprotocol_ptctrusted 7
#define Anum_pg_extprotocol_ptcacl 8

#define Natts_pg_extprotocol 8


#endif							/* PG_EXTPROTOCOL_D_H */
