#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for DDS algorithm
#
#  Copyright (c) 2019-2024 TeleDB Development Group
#
# IDENTIFICATION
#    $PostgreSQL$
#
#-------------------------------------------------------------------------

subdir = src/backend/pgxc/dds
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = dds.o

include $(top_srcdir)/src/backend/common.mk