#-------------------------------------------------------------------------
#
# Makefile for backend/unittest
#
# src/backend/unittest/backend/stub/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/unittest/backend/stub/
top_builddir = ../../../../..
include $(top_builddir)/src/Makefile.global

SUBDIRS = access utils
include $(top_srcdir)/src/backend/common.mk
