#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for optimizer/spm
#
# IDENTIFICATION
#    src/backend/optimizer/spm/Makefile
#-------------------------------------------------------------------------

subdir = src/backend/optimizer/spm
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = spm_gen_hints.o spm.o spm_cap.o spm_apply.o spm_evo.o spm_cache.o\

include $(top_srcdir)/src/backend/common.mk
