#-------------------------------------------------------------------------
#
# Makefile for backend/unittest
#
# src/backend/unittest/backend/storage/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/unittest/backend/storage/
top_builddir = ../../../../../
include $(top_builddir)/src/Makefile.global

SUBDIRS = lmgr
include $(top_srcdir)/src/backend/common.mk

clean:
