/* contrib/pgcrypto/pgcrypto--1.3--1.4.sql */

-- complain if script is sourced in psql, rather than via ALTER EXTENSION
\echo Use "ALTER EXTENSION pgcrypto UPDATE TO '1.4'" to load this file. \quit

CREATE OR REPLACE FUNCTION SM2_gen_skey()
RETURNS text
AS 'MODULE_PATHNAME', 'SM2_gen_skey'
LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE OR REPLACE FUNCTION SM2_gen_pkey(skey text)
RETURNS text
AS 'MODULE_PATHNAME', 'SM2_gen_pkey'
LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE OR REPLACE FUNCTION SM2_gen_key_pair()
RETURNS setof record
AS 'MODULE_PATHNAME', 'SM2_gen_key_pair'
LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE OR REPLACE FUNCTION SM2_enc(plain text, pkey text)
RETURNS text
AS 'MODULE_PATHNAME', 'SM2_enc'
LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE OR REPLACE FUNCTION SM2_dec(cipher text, skey text)
RETURNS text
AS 'MODULE_PATHNAME', 'SM2_dec'
LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE OR REPLACE FUNCTION SM3_hash(msg text)
RETURNS text
AS 'MODULE_PATHNAME', 'SM3_hash'
LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE OR REPLACE FUNCTION SM4_gen_key()
RETURNS text
AS 'MODULE_PATHNAME', 'SM4_gen_key'
LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE OR REPLACE FUNCTION SM4_gen_iv()
RETURNS text
AS 'MODULE_PATHNAME', 'SM4_gen_iv'
LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION SM4_enc(plain text, key text, iv text)
RETURNS text
AS 'MODULE_PATHNAME', 'SM4_enc'
LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION SM4_dec(cipher text, key text, iv text)
RETURNS text
AS 'MODULE_PATHNAME', 'SM4_dec'
LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;