#-------------------------------------------------------------------------
#
# Makefile for backend/unittest
#
# src/backend/unittest/backend/stub/access/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/unittest/backend/stub/access/
top_builddir = ../../../../../../
include $(top_builddir)/src/Makefile.global

SUBDIRS = transam
include $(top_srcdir)/src/backend/common.mk
