# Copyright (c) 2022-2026, PostgreSQL Global Development Group

vector_sources = files(
  'src/bitutils.c',
  'src/bitvec.c',
  'src/halfutils.c',
  'src/halfvec.c',
  'src/hnsw.c',
  'src/hnswbuild.c',
  'src/hnswinsert.c',
  'src/hnswscan.c',
  'src/hnswutils.c',
  'src/hnswvacuum.c',
  'src/ivfbuild.c',
  'src/ivfflat.c',
  'src/ivfinsert.c',
  'src/ivfkmeans.c',
  'src/ivfscan.c',
  'src/ivfutils.c',
  'src/ivfvacuum.c',
  'src/sparsevec.c',
  'src/vector.c',
)

vector_c_args = cc.get_supported_arguments(
  '-march=native',
  '-ftree-vectorize',
  '-fassociative-math',
  '-fno-signed-zeros',
  '-fno-trapping-math',
)

if host_system == 'windows'
  vector_sources += rc_lib_gen.process(win32ver_rc, extra_args: [
    '--NAME', 'vector',
    '--FILEDESC', 'vector - vector data type and IVFFlat/HNSW indexes',])
endif

vector = shared_module('vector',
  vector_sources,
  c_args: vector_c_args,
  kwargs: contrib_mod_args,
)
contrib_targets += vector

vector_sql = configure_file(
  input: 'sql/vector.sql',
  output: 'vector--0.8.6.sql',
  copy: true,
)

install_data(
  'vector.control',
  vector_sql,
  'sql/vector--0.1.0--0.1.1.sql',
  'sql/vector--0.1.1--0.1.3.sql',
  'sql/vector--0.1.3--0.1.4.sql',
  'sql/vector--0.1.4--0.1.5.sql',
  'sql/vector--0.1.5--0.1.6.sql',
  'sql/vector--0.1.6--0.1.7.sql',
  'sql/vector--0.1.7--0.1.8.sql',
  'sql/vector--0.1.8--0.2.0.sql',
  'sql/vector--0.2.0--0.2.1.sql',
  'sql/vector--0.2.1--0.2.2.sql',
  'sql/vector--0.2.2--0.2.3.sql',
  'sql/vector--0.2.3--0.2.4.sql',
  'sql/vector--0.2.4--0.2.5.sql',
  'sql/vector--0.2.5--0.2.6.sql',
  'sql/vector--0.2.6--0.2.7.sql',
  'sql/vector--0.2.7--0.3.0.sql',
  'sql/vector--0.3.0--0.3.1.sql',
  'sql/vector--0.3.1--0.3.2.sql',
  'sql/vector--0.3.2--0.4.0.sql',
  'sql/vector--0.4.0--0.4.1.sql',
  'sql/vector--0.4.1--0.4.2.sql',
  'sql/vector--0.4.2--0.4.3.sql',
  'sql/vector--0.4.3--0.4.4.sql',
  'sql/vector--0.4.4--0.5.0.sql',
  'sql/vector--0.5.0--0.5.1.sql',
  'sql/vector--0.5.1--0.6.0.sql',
  'sql/vector--0.6.0--0.6.1.sql',
  'sql/vector--0.6.1--0.6.2.sql',
  'sql/vector--0.6.2--0.7.0.sql',
  'sql/vector--0.7.0--0.7.1.sql',
  'sql/vector--0.7.1--0.7.2.sql',
  'sql/vector--0.7.2--0.7.3.sql',
  'sql/vector--0.7.3--0.7.4.sql',
  'sql/vector--0.7.4--0.8.0.sql',
  'sql/vector--0.8.0--0.8.1.sql',
  'sql/vector--0.8.1--0.8.2.sql',
  'sql/vector--0.8.2--0.8.3.sql',
  'sql/vector--0.8.3--0.8.4.sql',
  'sql/vector--0.8.4--0.8.5.sql',
  'sql/vector--0.8.5--0.8.6.sql',
  kwargs: contrib_data_args,
)

install_headers(
  'src/halfvec.h',
  'src/sparsevec.h',
  'src/vector.h',
  install_dir: dir_include_extension / 'vector',
)

tests += {
  'name': 'pgvector',
  'sd': meson.current_source_dir(),
  'bd': meson.current_build_dir(),
  'regress': {
    'sql': [
      'bit',
      'btree',
      'cast',
      'copy',
      'halfvec',
      'hnsw_bit',
      'hnsw_halfvec',
      'hnsw_sparsevec',
      'hnsw_vector',
      'ivfflat_bit',
      'ivfflat_halfvec',
      'ivfflat_vector',
      'sparsevec',
      'vector_type',
    ],
    'inputdir': meson.current_source_dir() / 'test',
    'expecteddir': meson.current_source_dir() / 'test',
    'regress_args': ['--load-extension=vector'],
  },
  'tap': {
    'tests': [
      'test/t/001_ivfflat_wal.pl',
      'test/t/002_ivfflat_vacuum.pl',
      'test/t/003_ivfflat_vector_build_recall.pl',
      'test/t/004_ivfflat_vector_insert_recall.pl',
      'test/t/005_ivfflat_query_recall.pl',
      'test/t/006_ivfflat_lists.pl',
      'test/t/007_ivfflat_inserts.pl',
      'test/t/008_ivfflat_centers.pl',
      'test/t/009_ivfflat_filtering.pl',
      'test/t/010_hnsw_wal.pl',
      'test/t/011_hnsw_vacuum.pl',
      'test/t/012_hnsw_vector_build_recall.pl',
      'test/t/013_hnsw_vector_insert_recall.pl',
      'test/t/014_hnsw_vector_vacuum_recall.pl',
      'test/t/015_hnsw_vector_duplicates.pl',
      'test/t/016_hnsw_inserts.pl',
      'test/t/017_hnsw_filtering.pl',
      'test/t/018_aggregates.pl',
      'test/t/019_storage.pl',
      'test/t/020_hnsw_bit_build_recall.pl',
      'test/t/021_hnsw_bit_insert_recall.pl',
      'test/t/022_hnsw_bit_vacuum_recall.pl',
      'test/t/023_hnsw_bit_duplicates.pl',
      'test/t/024_hnsw_halfvec_build_recall.pl',
      'test/t/025_hnsw_halfvec_insert_recall.pl',
      'test/t/026_hnsw_halfvec_vacuum_recall.pl',
      'test/t/027_hnsw_halfvec_duplicates.pl',
      'test/t/028_hnsw_sparsevec_build_recall.pl',
      'test/t/029_hnsw_sparsevec_insert_recall.pl',
      'test/t/030_hnsw_sparsevec_vacuum_recall.pl',
      'test/t/031_hnsw_sparsevec_duplicates.pl',
      'test/t/032_ivfflat_halfvec_build_recall.pl',
      'test/t/033_comparison.pl',
      'test/t/034_distance_functions.pl',
      'test/t/035_ivfflat_bit_build_recall.pl',
      'test/t/036_ivfflat_bit_centers.pl',
      'test/t/037_inputs.pl',
      'test/t/038_hnsw_sparsevec_vacuum_insert.pl',
      'test/t/039_hnsw_cost.pl',
      'test/t/040_ivfflat_cost.pl',
      'test/t/041_ivfflat_iterative_scan.pl',
      'test/t/042_ivfflat_iterative_scan_recall.pl',
      'test/t/043_hnsw_iterative_scan.pl',
      'test/t/044_hnsw_iterative_scan_recall.pl',
      'test/t/045_hnsw_low_memory_build.pl',
      'test/t/045_ivfflat_scan_heap.pl',
      'test/t/046_hnsw_vacuum_scan.pl',
      'test/t/047_hnsw_vacuum_insert.pl',
      'test/t/048_ivfflat_vacuum_insert.pl',
    ],
  },
}
