#-------------------------------------------------------------------------
#
# Makefile for src/pl/oraplsql (PostgreSQL's SQL procedural language)
#
# Copyright (c) 1994, Regents of the University of California
#
# src/pl/oraplsql/Makefile
#
#-------------------------------------------------------------------------

subdir = src/pl/oraplsql
top_builddir = ../../..
include $(top_builddir)/src/Makefile.global

SUBDIRS = src

$(recurse)
