#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for utils/xact_whitebox
#
# IDENTIFICATION
#    src/backend/utils/xact_whitebox/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/utils/xact_whitebox
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = xact_whitebox.o xact_whitebox_stubnames.o

include $(top_srcdir)/src/backend/common.mk
