#ifdef USE_WHITEBOX_INJECTION
/* changed with Stub indexs */
char * XactWhiteBoxStubNames[] = 
{
	"<unassigned:0>",
	"REMOTE_PREPARE_SEND_ALL_FAILED",
	"REMOTE_PREPARE_SEND_LAST_DN_FAILED",
	"REMOTE_PREPARE_SEND_LAST_CN_FAILED",
	"REMOTE_PREPARE_MESSAGE_REPEAT_CN",
	"REMOTE_PREPARE_MESSAGE_REPEAT_DN",
	"REMOTE_PREPARE_FAILED_AFTER_SEND",
	"REMOTE_COMMIT_SEND_ALL_FAILED",
	"REMOTE_COMMIT_SEND_LAST_CN_FAILED",
	"REMOTE_COMMIT_SEND_LAST_DN_FAILED",
	"REMOTE_COMMIT_MESSAGE_REPEAT_CN",
	"REMOTE_COMMIT_MESSAGE_REPEAT_DN",
	"REMOTE_COMMIT_FAILED_AFTER_SEND",
	"REMOTE_ABORT_SEND_ALL_FAILED",
	"REMOTE_ABORT_SEND_LAST_CN_FAILED",
	"REMOTE_ABORT_SEND_LAST_DN_FAILED",
	"REMOTE_ABORT_MESSAGE_REPEAT_CN",
	"REMOTE_ABORT_MESSAGE_REPEAT_DN",
	"REMOTE_ABORT_FAILED_AFTER_SEND",
	"SAVEPOINT_DEFINE_FAILED",
	"SAVEPOINT_RELEASE_FAILED",
	"SAVEPOINT_ROLLBACK_FAILED",
	"SYNC_REPLICATE_CYCLE",
	"XLOG_FLUSH",
	"WAL_SENDER_MAINLOOP",
	"WAL_RECEIVER_PROCESS_DATA",
	"LOCAL_COMMIT_PREPARED_FAILED",
	"LOCAL_ABORT_PREPARED_FAILED",
	"GET_GTS_FAILED",
	"LOCAL_PREPARED_FAILED_A",
	"LOCAL_PREPARED_FAILED_B",
	"LOCAL_PREPARED_CLOG_FAILED",
	"LOCAL_PREPARED_TWOPHASEFILE_FAILED",
	"LOCAL_PREPARE_TRANSACTION_BLOCK",
	"PUSH_TRANSACTION_BEFORE_PUSH_FAILED",
	"PUSH_TRANSACTION_AFTER_PUSH_FAILED",
	"LOCAL_COMMIT_SUBTRANSACTION_FAILED",
	"LOCAL_ABORT_SUBTRANSACTION_FAILED",
	"SYNC_REL_RECEIVE_CANCELED",
	"AFTER_REMOTE_COMMIT_FAILED",
	"AFTER_ALL_COMMIT_FAILED",
	"LOCAL_PREPARED_XLOG",
	"PRIMARY_CHECKPOINT_KEEP_XLOG",
	"STANDBY_XLOGREDO_KEEP_XLOG"
};


char * InjectionFailureTypeStrings[] =
{
	"INACTIVE",
	"ERROR",
	"FATAL",
	"PANIC",
	"SLEEP"
};

char * InjectionFailureNodeStrings[] =
{
	"LOCAL_CN",
	"ONE_CN",
	"ALL_CN",
	"ONE_DN",
	"ALL_DN",
	"ALL_NODE"
};


char * InjectionFailureErrorLevelStrings[] =
{
	"NOERROR",
	"ERROR",
	"FATAL",
	"PANIC"
};

/* 
 * Stubs here defined for sleep only purpose.
 * See InjectionSleepOnlyStubIndex.
 */
char * InjectionSleepOnlyStub[] =
{
	"SYNC_REPLICATE_CYCLE",
	"XLOG_FLUSH",
	"WAL_SENDER_MAINLOOP",
	"WAL_RECEIVER_PROCESS_DATA"
};
#endif
