#-------------------------------------------------------------------------
#
# src/backend/utils/mb/conversion_procs/utf8_and_gb18030/Makefile
#
#-------------------------------------------------------------------------
subdir = src/backend/utils/mb/conversion_procs/utf8_and_gb18030_2022
top_builddir = ../../../../../..
include $(top_builddir)/src/Makefile.global

NAME		= utf8_and_gb18030_2022
PGFILEDESC	= "utf8 <-> gb18030_2022 text conversions"

include $(srcdir)/../proc.mk
