#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for DDS dependency shared memory bucket
#
#  Copyright (c) 2019-2024 TeleDB Development Group
#
# IDENTIFICATION
#    $PostgreSQL$
#
#-------------------------------------------------------------------------

subdir = src/backend/storage/bucket
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = dds_dependency.o

include $(top_srcdir)/src/backend/common.mk