#-------------------------------------------------------------------------
#
# Makefile for backend/forward
#
# src/backend/forward/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/forward
top_builddir = ../../..
include $(top_builddir)/src/Makefile.global

OBJS 	= fnconn.o
SUBDIRS	= storage

include $(top_srcdir)/src/backend/common.mk
