#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for backend/nodes
#
# IDENTIFICATION
#    src/backend/nodes/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/license
top_builddir = ../../..
include $(top_builddir)/src/Makefile.global

OBJS = license.o

include $(top_srcdir)/src/backend/common.mk

#install-data: installdirs
#	$(INSTALL_DATA) $(srcdir)/public.key '$(DESTDIR)$(datadir)/public.key'

#installdirs:
#	$(MKDIR_P) '$(DESTDIR)$(datadir)'