#-------------------------------------------------------------------------
#
# Makefile for backend/unittest
#
# src/backend/unittest/backend/stub/utils/cache
#
#-------------------------------------------------------------------------

subdir = src/backend/unittest/backend/stub/access/transam
top_builddir = ../../../../../../../
include $(top_builddir)/src/Makefile.global
include $(top_srcdir)/src/backend/common.mk

STUB_OBJS = stub_relcache.o

include $(top_srcdir)/src/backend/unittest/make_stub.mk
