#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for utils/opentenbase_test
#
# IDENTIFICATION
#    src/backend/utils/opentenbase_test/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/utils/opentenbase_test
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = opentenbase_test.o

include $(top_srcdir)/src/backend/common.mk
