#-------------------------------------------------------------------------
#
# Makefile for backend/oracle
#
# src/backend/oracle/Makefile
#
# Copyright (c) 2023 THL A29 Limited, a Tencent company.
#
# This source code file is licensed under the BSD 3-Clause License,
# you may obtain a copy of the License at http://opensource.org/license/bsd-3-clause/
#
#-------------------------------------------------------------------------

subdir = src/backend/oracle
top_builddir = ../../..
include $(top_builddir)/src/Makefile.global

OBJS = others.o datefce.o plvstr.o convert.o charpad.o 

include $(top_srcdir)/src/backend/common.mk