#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for forward/storage
#
# IDENTIFICATION
#    src/backend/forward/storage/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/forward/storage
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = fnbufmgr.o fnbuf_init.o fnbufpage.o fnfreelist.o
include $(top_srcdir)/src/backend/common.mk
