\c postgres

-- catalog check
select oid,relname,relnamespace,reloftype,relowner,relam,relfilenode,reltablespace,reltoastrelid,relstashrelid,relstashidxid,relregistryrelid,relregistryidxid,relhasindex,relisshared,relpersistence,relkind,relnatts,relchecks,relhasoids, relhaspkey,relhasclusterkey,relhasrules,relhastriggers,relhassubclass,relrowsecurity,relforcerowsecurity,relispopulated,relreplident,relispartition,relrowidseq,relhasextent,relstore,relflags,relpartkind,relparent,relpartbound  from pg_class where oid < 10000 order by 1;
select * from pg_default_acl;
select * from pg_pltemplate order by 1;
select * from pg_tablespace where oid < 10000 order by 1;
select * from pg_shdepend where dbid = 0 and refobjid < 10000 order by 5,6,7;
select oid,* from pg_type where oid < 10000 order by 1;
select typname,pg_namespace.nspname, typowner, typbyval, typtype, typcategory, typispreferred, typisdefined, typdelim,typinput,typoutput,typreceive,typsend,typmodin,typmodout,typanalyze,typalign,typstorage,typnotnull,typbasetype,typtypmod,typndims,typcollation,typdefaultbin,typdefault,typacl from pg_type join pg_namespace on pg_type.typnamespace = pg_namespace.oid where pg_type.oid >= 10000 and pg_type.oid < 16384 and pg_type.typname not like 'pg_toast%' order by 1,2;
select attrelid,attname,atttypid,attstattarget,attlen,attnum,attndims,attcacheoff,atttypmod,attbyval,attstorage,attalign,attnotnull,atthasdef,atthasmissing,attidentity,attisdropped,attislocal,attinhcount,attcollen,atttranscomp,atttranscomplevel,attlwcomp,attuniquestore,attcollation,attoptions,attfdwoptions,attmissingval from pg_attribute where attrelid < 10000 order by 1,2;
select oid,* from pg_catalog.pg_proc where oid < 10000 and proacl is null order by 1;
select oid,proname,pronamespace,proowner,prolang,procost,prorows,provariadic,protransform,prokind,prosecdef,proleakproof,proisstrict,proretset,provolatile,proparallel,pronargs,pronargdefaults,prorettype,proargtypes,proallargtypes,proargmodes,proargnames,proargdefaults,protrftypes,prosrc,probin,proconfig from pg_catalog.pg_proc where oid < 10000 and proacl is not null order by 1;
select oid,rolname,rolsuper,rolinherit,rolcreaterole,rolcreatedb,rolcanlogin,rolreplication,rolbypassrls,rolcreateprof,rolprofile,rolconnlimit,rolresqueue,rolvaliduntil,rolresgroup,rolpriority from pg_authid where oid < 10000 and oid != 10 order by 1;
select oid,rolsuper,rolinherit,rolcreaterole,rolcreatedb,rolcanlogin,rolreplication,rolbypassrls,rolcreateprof,rolprofile,rolconnlimit,rolresqueue,rolvaliduntil,rolresgroup,rolpriority from pg_authid where oid = 10;
select * from pg_auth_members where roleid < 10000 order by 1;
select oid,datname,datdba,encoding,datistemplate,datallowconn,datconnlimit,dattablespace,datsqlmode from pg_database where oid < 10000 order by 1;
select datname,datdba,encoding,datistemplate,datallowconn,datconnlimit,dattablespace,datsqlmode from pg_database where oid > 10000 and oid < 16384 order by 1;
select oid, * from pg_user_mapping where oid < 16384;
select * from pg_shdescription where objoid < 10000 order by 1;
select classoid, description from pg_shdescription where objoid > 10000 and objoid < 16384 order by 1, 2;
select * from pg_aggregate order by 1,2,3,4;
select oid,* from pg_am order by 1;
select * from pg_amop order by 1,2,3,4;
select * from pg_amproc order by 1,2,3,4;
select * from pg_attrdef where adrelid < 16384;
select * from pg_cast order by 1,2,3,4;
select conname,contype,condeferrable,condeferred,convalidated,conrelid,conindid,confrelid,confupdtype,confdeltype,confmatchtype,conislocal,coninhcount,connoinherit,conisenable,conkey,confkey,conpfeqop,conppeqop,conffeqop,conexclop,conbin,consrc from pg_constraint where connamespace < 16384 order by 1;
select * from pg_conversion where oid < 16384 order by 1;
select * from pg_description where objoid < 10000 order by 2,1;
select indexrelid,indrelid,indnatts,indisunique,indisprimary,indisexclusion,indimmediate,indisclustered,indisvalid,indcheckxmin,indisready,indislive,indisreplident,indkey,indcollation,indexprs,indpred from pg_index where indrelid < 10000 order by 1,2;
select oid,* from pg_language where oid < 10000 order by 1;
select * from pg_language where oid > 10000 and oid < 16384;
select oid,nspname,nspowner from pg_namespace where oid < 10000 order  by 1;
select nspname,nspowner from pg_namespace where oid > 10000 and oid < 16384 and nspname not like 'pg_temp%' and nspname not like 'pg_toast_temp%' order by 1;
select * from pg_opclass order by 1,2;
select * from pg_operator order by 1,7,8,9;
select oid,* from pg_opfamily order by 1;
select * from pg_extension where oid < 16384;
select oid, * from pg_collation where oid < 10000 order by 1;
select * from pg_range order by 1;
select dictname,dictnamespace,dictowner,dictinitoption from pg_ts_dict order by 1;
select oid,* from pg_ts_parser;
select * from pg_ts_config order by 1;
select * from pg_ts_config_map where mapcfg < 10000 order by 1,2;
select oid,* from pg_ts_template where oid < 10000;
select oid,* from pg_resgroup order by 1;
select * from pg_resgroupcapability order by 1;
select schemaname,viewname from pg_views order by 1,2;

-- view check, no error is ok
select * from pg_roles where rolname = 'audit_admin';
select usename,usesysid,usecreatedb,usesuper,userepl,usebypassrls,resqueue,valuntil,useconfig from pg_shadow where usename = 'audit_admin';
select * from pg_group order by 1 limit 1;
select * from pg_user where usename = 'audit_admin';
select * from pg_policies order by 1,2 limit 1;
select * from pg_rules order by 1,2,3 limit 1;
select schemaname,viewname from pg_views order by 1,2 limit 1;
select schemaname,tablename from pg_tables where schemaname = 'information_schema' order by 1,2 limit 1;
select * from pg_matviews order by 1,2 limit 1;
select schemaname,tablename,indexname from pg_indexes where schemaname = 'pg_catalog' order by 1,2,3 limit 1;
select * from pg_sequences where schemaname = 'pg_catalog' order by 1,2 limit 1;
select * from pg_stats order by 1,2,3,4 limit 1;
select * from pg_publication_tables order by 1,2,3 limit 1;
select locktype from pg_locks where locktype = 'relation' order by 1 limit 1;
select * from pg_cursors order by 1,2 limit 1;
select * from pg_available_extensions where name='bloom';
select * from pg_available_extension_versions where name='bloom';
select * from pg_prepared_xacts order by 2 limit 1;
select * from pg_prepared_statements order by 1limit 1;
select * from pg_seclabels order by 1,2,3 limit 1;
select * from pg_settings order by 1 limit 1;
select name from pg_file_settings where name='datestyle' limit 1;
select * from pg_hba_file_rules order by 1,2,3 limit 1;
select abbrev,is_dst from pg_timezone_abbrevs order by 1 limit 1;
select name,abbrev,is_dst from pg_timezone_names order by 1 limit 1;
select name from pg_config order by 1 limit 1;
select schemaname,relname from pg_stat_all_tables where schemaname = 'information_schema' order by 1,2 limit 1;
select schemaname,relname from pg_stat_xact_all_tables where schemaname = 'information_schema' order by 1,2 limit 1;
select schemaname,relname from pg_stat_sys_tables order by 1,2 limit 1;
select schemaname,relname from pg_stat_xact_sys_tables order by 1,2 limit 1;
select schemaname,relname from pg_stat_user_tables where schemaname='squeeze' order by 1,2 limit 1;
select schemaname,relname from pg_stat_xact_user_tables where schemaname='squeeze' order by 1,2 limit 1;
select schemaname,relname from pg_statio_all_tables where schemaname = 'information_schema' order by 1,2 limit 1;
select schemaname,relname from pg_statio_sys_tables where schemaname = 'information_schema' order by 1,2 limit 1;
select schemaname,relname from pg_statio_user_tables where schemaname='squeeze' order by 1,2 limit 1;
select schemaname,relname,indexrelname from pg_stat_all_indexes  where schemaname = 'pg_catalog' order by 1,2,3 limit 1;
select schemaname,relname,indexrelname from pg_stat_sys_indexes order by 1,2,3 limit 1;
select schemaname,relname,indexrelname from pg_stat_user_indexes where schemaname='squeeze' order by 1,2,3 limit 1;
select schemaname,relname,indexrelname from pg_statio_all_indexes where schemaname='pg_catalog' order by 1,2,3 limit 1;
select schemaname,relname,indexrelname from pg_statio_sys_indexes order by 1,2,3 limit 1;
select schemaname,relname,indexrelname from pg_statio_user_indexes where schemaname='squeeze' order by 1,2,3 limit 1;
select schemaname,relname from pg_statio_all_sequences where schemaname='squeeze' order by 1,2 limit 1;
select * from pg_statio_sys_sequences order by 1,2,3 limit 1;
select schemaname,relname from pg_statio_user_sequences where schemaname='squeeze' order by 1,2 limit 1;
select datid, wait_event from pg_stat_activity order by 2 limit 1;
select datid, wait_event from pg_stat_cluster_activity order by 2 limit 1;
select datid, wait_event from pg_stat_cluster_activity_onlycn order by 2 limit 1;
select usesysid, state from pg_stat_replication order by 1;
select * from pg_stat_wal_receiver limit 1;
select * from pg_stat_subscription limit 1;
select ssl, version from pg_stat_ssl limit 1;
select * from pg_replication_slots limit 1;
select datid, datname  from pg_stat_database order by 1 limit 1;
select datid, datname,confl_tablespace, confl_lock from pg_stat_database_conflicts order by 1 limit 1;
select * from pg_stat_user_functions limit 1;
select * from pg_stat_xact_user_functions limit 1;
select archived_count from pg_stat_archiver order by 1 limit 1;
select * from pg_stat_progress_vacuum order by 2 limit 1;
select * from pg_user_mappings order by 1 limit 1;
select * from pg_replication_origin_status limit 1;
select * from dual limit 1;
select * from pg_resgroup_config limit 1;
select * from pg_resgroup_status limit 1;
select * from pg_stat_cluster_context_memory_detail limit 1;
select * from pg_stat_cluster_query_workfile_usage limit 1;
select diskspace from pg_stat_cluster_workfile_diskspace limit 1;
select * from pg_stat_query_workfile_usage limit 1;
select diskspace from pg_stat_workfile_diskspace limit 1;
select * from pg_resgroup_cluster_clean_slot limit 1;
select * from pg_resgroup_cluster_clean_slot_onlycn limit 1;
select * from pg_xact_relstat_info;
select * from information_schema.information_schema_catalog_name limit 1;
select * from information_schema.applicable_roles limit 1;
select * from information_schema.administrable_role_authorizations limit 1;
select * from information_schema.attributes where udt_schema = 'pg_catalog' limit 1;
select character_set_catalog,character_set_schema,character_set_name,character_repertoire,form_of_use,default_collate_catalog,default_collate_schema from information_schema.character_sets limit 1;
select * from information_schema.check_constraint_routine_usage limit 1;
select * from information_schema.check_constraints limit 1;
select * from information_schema.collations limit 1;
select * from information_schema.collation_character_set_applicability limit 1;
select * from information_schema.column_domain_usage order by 1,2,3,4,5,6,7 limit 1;
select table_catalog,table_name from information_schema.column_privileges order by 1,2 limit 1;
select * from information_schema.column_udt_usage limit 1;
select * from information_schema.columns limit 1;
select table_catalog,table_schema,table_name from information_schema.constraint_column_usage where table_schema = 'squeeze' order by 1,2,3 limit 1;
select table_catalog,table_schema,table_name from information_schema.constraint_table_usage where table_schema = 'squeeze' order by 1,2,3 limit 1;
select * from information_schema.domain_constraints limit 1;
select * from information_schema.domain_udt_usage limit 1;
select * from information_schema.domains order by 1,2,3 limit 1;
select constraint_catalog,constraint_schema,constraint_name from information_schema.key_column_usage where constraint_schema = 'squeeze' order by 1,2,3 limit 1;
select * from information_schema.parameters limit 1;
select constraint_catalog,constraint_schema,constraint_name from information_schema.referential_constraints order by 1,2,3 limit 1;
select table_catalog,table_schema,table_name from information_schema.role_column_grants where table_schema = 'information_schema' order by 1,2,3 limit 1;
select specific_catalog,specific_schema,specific_name from information_schema.routine_privileges order by 1,2,3 limit 1;
select specific_catalog,specific_schema,specific_name from information_schema.role_routine_grants order by 1,2,3 limit 1;
select * from information_schema.routines limit 1;
select catalog_name, schema_name from information_schema.schemata order by 1,2 limit 1;
select * from information_schema.sequences where sequence_schema = 'information_schema' limit 1;
select * from information_schema.table_constraints where constraint_schema = 'pg_catalog' order by 1,2,3 limit 1;
select table_catalog,table_schema,table_name from information_schema.table_privileges order by 3 limit 1;
select table_catalog,table_schema,table_name from information_schema.role_table_grants order by 3 limit 1;
select * from information_schema.tables where table_schema = 'information_schema' order by 1,2,3 limit 1;
select * from information_schema.transforms limit 1;
select * from information_schema.triggered_update_columns limit 1;
select * from information_schema.triggers limit 1;
select udt_catalog,udt_schema,udt_name from information_schema.udt_privileges where udt_schema = 'information_schema' order by 1,2,3 limit 1;
select udt_catalog,udt_schema,udt_name from information_schema.role_udt_grants where udt_schema = 'information_schema' order by 1,2,3 limit 1;
select object_catalog,object_schema,object_name from information_schema.usage_privileges order by 1,2,3 limit 1;
select object_catalog,object_schema,object_name from information_schema.role_usage_grants order by 1,2,3 limit 1;
select * from information_schema.user_defined_types  where user_defined_type_schema = 'pg_catalog' limit 1;
select * from information_schema.view_column_usage order by 1,2,3 limit 1;
select table_catalog,table_schema,table_name from information_schema.view_routine_usage order by 1,2,3 limit 1;
select * from information_schema.view_table_usage order by 1,2,3 limit 1;
select * from information_schema.views order by 1,2,3 limit 1;
select * from information_schema.data_type_privileges order by 1,2,3 limit 1;
select * from information_schema.element_types order by 1,2,3 limit 1;
select * from information_schema._pg_foreign_table_columns limit 1;
select * from information_schema.column_options limit 1;
select * from information_schema._pg_foreign_data_wrappers limit 1;
select * from information_schema.foreign_data_wrapper_options limit 1;
select * from information_schema.foreign_data_wrappers limit 1;
select * from information_schema._pg_foreign_servers limit 1;
select * from information_schema.foreign_server_options limit 1;
select * from information_schema.foreign_servers limit 1;
select * from information_schema._pg_foreign_tables limit 1;
select * from information_schema.foreign_table_options limit 1;
select * from information_schema.foreign_tables limit 1;
select * from information_schema._pg_user_mappings limit 1;
select * from information_schema.user_mapping_options limit 1;
select * from information_schema.user_mappings limit 1;

-- 3.16.3.20 test
select * from fn_stat_get_page() where qid_ts_node=0 and qid_seq=0 limit 1;
select * from fn_stat_clear_page(0,0);

\c postgres audit_admin
select * from pg_audit_stmt_conf_detail limit 1;
select * from pg_audit_obj_conf_detail limit 1;
select * from pg_audit_obj_def_opts_detail limit 1;
select * from pg_audit_user_conf_detail limit 1;
select * from pg_audit_fga_conf_detail limit 1;
select * from pg_audit_fga_policy_columns_detail limit 1;
