#-------------------------------------------------------------------------
#
# Makefile for backend/unittest
#
# src/backend/unittest/backend/utils/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/unittest/backend/utils
top_builddir = ../../../../../
include $(top_builddir)/src/Makefile.global

SUBDIRS = resowner misc time cache
include $(top_srcdir)/src/backend/common.mk

clean:
	rm -rf $(UNIT_OBJS)
